routes/web.php
Route::any('/transaction/detailList/', 'TransactionController@detailList')->name('Transaction.detailList');
/*
|--------------------------------------------------------------------------
| PanelUserController
|--------------------------------------------------------------------------
*/

Route::prefix('panel/user')->name('panel.user.')->namespace('panel')->group(function () {
    Route::get('insert', 'UserPanelController@insert')->name('insert');
    Route::post('store', 'UserPanelController@store')->name('store');
    Route::any('update', 'UserPanelController@update')->name('update');
    Route::any('updatePass', 'UserPanelController@updatePass')->name('updatePass');
    Route::any('RestorePass', 'UserPanelController@RestorePass')->name('RestorePass');
    Route::any('delete', 'UserPanelController@delete')->name('delete');
    Route::any('list', 'UserPanelController@list')->name('list');
    Route::any('/listhome', 'UserPanelController@listhome')->name('listhome');
    Route::any('show', 'UserPanelController@show')->name('show');
    Route::get('login', function () {
        return view('panel.login');
    });
    Route::any('/insert', 'UserPanelController@insert')->name('insert');
    Route::any('/insertajax', 'UserPanelController@insertajax')->name('insertajax');
    Route::post('storeUser', 'UserPanelController@storeUser')->name('storeUser');
    Route::any('/updateajax', 'UserPanelController@updateAjax')->name('updateAjax');
    Route::any('login', 'UserPanelController@login')->name('login');
    Route::get('login', 'UserPanelController@logout')->name('logout');
    Route::any('home', 'UserPanelController@home')->name('home');
    Route::any('permission', 'UserPanelController@permission')->name('permission');
    // Route::any('home', 'UserPanelController@home')->name('home');
});

/*
|--------------------------------------------------------------------------
//GroupController
|--------------------------------------------------------------------------
*/

Route::prefix('panel/group')->name('panel.group.')->namespace('panel')->group(function () {
    Route::get('insert/', 'GroupController@insert')->name('insert')->middleware('permission:GroupController@insert');
    Route::post('insert/', 'GroupController@store')->name('store')->middleware('permission:GroupController@store');
    Route::put('edit/', 'GroupController@update')->name('update')->middleware('permission:GroupController@update');
    Route::delete('delete/', 'GroupController@delete')->name('delete')->middleware('permission:GroupController@delete');
    Route::get('show/{Group}', 'GroupController@show')->name('show')->middleware('permission:GroupController@show');
});

/*
|--------------------------------------------------------------------------
| UserGroupController
|--------------------------------------------------------------------------
*/

Route::prefix('panel/user-group')->name('panel.usergroup.')->namespace('panel')->group(function () {
    Route::get('insert/', 'UserGroupController@insert')->name('insert')->middleware('permission:UserGroupController@insert');
    Route::post('insert/', 'UserGroupController@store')->name('store')->middleware('permission:UserGroupController@store');
    Route::put('edit/', 'UserGroupController@update')->name('update')->middleware('permission:UserGroupController@update');
    Route::delete('delete/', 'UserGroupController@delete')->name('delete')->middleware('permission:UserGroupController@delete');
    Route::get('show/{UserGroup}', 'UserGroupController@show')->name('show')->middleware('permission:UserGroupController@show');
});

/*
|--------------------------------------------------------------------------
//MethodController
|--------------------------------------------------------------------------
*/

Route::prefix('panel/method')->name('panel.method.')->namespace('panel')->group(function () {
    Route::get('insert/', 'MethodController@insert')->name('insert')->middleware('permission:MethodController@insert');
    Route::post('insert/', 'MethodController@store')->name('store');
    Route::put('edit/', 'MethodController@update')->name('update');
    Route::delete('delete/', 'MethodController@delete')->name('delete');
    Route::get('show/', 'MethodController@show')->name('show');
});


/*
|--------------------------------------------------------------------------
/PermissionGroupController
|--------------------------------------------------------------------------
*/

Route::prefix('panel/permission-group')->name('panel.permissiongroup.')->namespace('panel')->group(function () {
    Route::any('insert/', 'PermissionGroupController@insert')->name('insert')->middleware('permission:PermissionGroupController@insert');
    Route::post('insert/', 'PermissionGroupController@store')->name('store')->middleware('permission:PermissionGroupController@insert');
    Route::put('edit/', 'PermissionGroupController@update')->name('update')->middleware('permission:PermissionGroupController@insert');
    Route::delete('delete/', 'PermissionGroupController@delete')->middleware('permission:PermissionGroupController@insert');
    Route::get('show/', 'PermissionGroupController@show')->middleware('permission:PermissionGroupController@insert');
    Route::any('/ajax', 'PermissionGroupController@ajax')->name('ajax');
    Route::any('insertajax/', 'PermissionGroupController@ajaxStore')->name('ajaxStore')->middleware('permission:PermissionGroupController@ajaxStore');
});


/*
|--------------------------------------------------------------------------
//PermissionUserController
|--------------------------------------------------------------------------
*/

Route::prefix('panel/permission-user')->name('panel.permissionuser.')->namespace('panel')->group(function () {
    Route::any('insert/', 'PermissionUserController@insert')->name('insert');
    Route::post('insert/', 'PermissionUserController@store')->name('store');
    Route::put('edit/', 'PermissionUserController@update');
    Route::delete('delete/', 'PermissionUserController@delete');
    Route::get('show/', 'PermissionUserController@show');
    Route::any('/ajax', 'PermissionUserController@ajax')->name('ajax');

});

/*
 * //TaxiController

 */
Route::prefix('panel/taxi')->name('panel.taxi.')->namespace('panel')->group(function () {
    Route::any('requestTaxi/', 'TaxiController@request')->name('request');
    Route::any('chooseSelectedPlace/','TaxiController@chooseSelectedPlace')->name('chooseSelectedPlace');
    Route::any('calculatePrice/', 'TaxiController@calculatePrice')->name('calculatePrice');
    Route::any('requestService/', 'TaxiController@requestService')->name('requestService');
    Route::any('requestRefresh/', 'TaxiController@requestRefresh')->name('requestRefresh');
    Route::any('search/', 'TaxiController@search')->name('search');
    Route::any('storeTrip/', 'TaxiController@storeTrip')->name('storeTrip');
    Route::any('storeSelectedPlace/','TaxiController@storeSelectedPlace')->name('storeSelectedPlace');
    Route::any('currentRequest/','TaxiController@currentRequest')->name('currentRequest');
    Route::any('countRequest/','TaxiController@countRequest')->name('countRequest');
});
/*
|--------------------------------------------------------------------------
|  //tourism
|--------------------------------------------------------------------------
*/

Route::prefix('panel/tourism')->name('panel.tourism.')->namespace('panel')->group(function () {
    Route::any('storeTypeCategory/', 'tourismController@storeTypeCategory')->name('storeTypeCategory');
    Route::any('typeCategory/', 'tourismController@typeCategory')->name('typeCategory');
    Route::any('listTypeCategory', 'tourismController@listTypeCategory')->name('listTypeCategory');
    Route::any('listCity', 'tourismController@listCity')->name('listCity');
    Route::any('homeTourism/{id}/{cityId}', 'tourismController@homeTourism')->name('homeTourism');
    Route::any('placeInfo/{id?}', 'tourismController@placeInfo')->name('placeInfo');
    Route::any('storeCategoryPlace', 'tourismController@storeCategoryPlace')->name('storeCategoryPlace');
    Route::any('editCategoryPlace', 'tourismController@editCategoryPlace')->name('editCategoryPlace');
});
/*
|--------------------------------------------------------------------------
| Fast Test
|--------------------------------------------------------------------------
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/','HomeController@index');







/*
|--------------------------------------------------------------------------
| Finotech
|--------------------------------------------------------------------------
*/
    Route::get('finotech/panel-finotech-cc', 'FinoTechController@panelFinotechCc')->name('panelFinotech');
    Route::get('finotech/panel-finotech-ac', 'FinoTechController@panelFinotechAc')->name('panelFinotechAc');
    Route::get('bank-confirmation', 'FinoTechController@bankConfirmation');
    Route::get('finotech/get_wages', 'FinoTechController@getBankInfo');
    Route::get('finotech/get-authorization-code', 'FinoTechController@getAuthorizationCode');
    Route::get('finotech/deposit-to-card', 'FinoTechController@depositToCard');

/*
|--------------------------------------------------------------------------
| Charity
|--------------------------------------------------------------------------
*/

    Route::resource('charity',CharityController::class)->except('index');
    Route::any('charity','CharityController@index')->name('charity.index');

/*
|--------------------------------------------------------------------------
| AirFare
|--------------------------------------------------------------------------
*/
    Route::get('airfare','AirFareController@selectCity');
    Route::get('airfare/edit','AirFareController@editCity');
    Route::post('airfare/update','AirFareController@updateCity');
    Route::post('airfare/delete','AirFareController@deleteCity');

app/Http/Controllers/api/v1/FinoTechController.php
<?php

namespace App\Http\Controllers\api\v1;


use App\Models\CardInformation;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Notifications\Notifiable;

class FinoTechController extends Controller
{
    use Notifiable;
    public $address = "https://apibeta.finnotech.ir/";
    public $url = "https://apibeta.finnotech.ir/dev/v2/oauth2/token";
    public $debug = false;
    public $clientId = "newcash1";
    public $scopes = "";
    public $nid = "0682364223";


    public function cardInformation(Request $request)
    {
        $url = 'https://apibeta.finnotech.ir/mpg/v2/clients/' . $this->clientId . '/cards/' . $request->card;
        $response = $this->curlResponseCardInfo($url, $request->tokenMiddleware);
        $responseObject = json_decode($response);
        if ($responseObject->status == 'DONE' && $responseObject->result->name) {
            CardInformation::create([
                'user_id' => $request->user()->user_id,
                'track_id' => $responseObject->trackId,
                'card_number' => $request->card,
                'name' => $responseObject->result->name,
                'do_time' => $responseObject->result->doTime
            ]);
            return response()->json([
                "data"=>['name'=>$responseObject->result->name]
            ]);
        }
        return response()->error('استعلام نا موفق بود');
    }

    public function curlResponseCardInfo($sendUrl, $token)
    {
        $curl = curl_init();
        curl_setopt_array($curl, array(
            CURLOPT_URL => $sendUrl,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => "",
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 0,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => "GET",
            CURLOPT_HTTPHEADER => array(
                "Accept: application/json",
                "Content-Type: application/json",
                "Authorization: Bearer " . $token
            ),
        ));
        $response = curl_exec($curl);
        curl_close($curl);
        return $response;
    }
}

app/Http/Livewire/Charity/Table.php
<?php

namespace App\Http\Livewire\Charity;

use App\Models\Charity;
use Livewire\Component;
use Livewire\WithPagination;

class Table extends Component
{
    use WithPagination;

    public $charityId;


    public function setCharityId($charityId)
    {
        $this->charityId = $charityId;
    }

    public function refresh()
    {

    }

    public function render()
    {
        $charities = Charity::where('created_at', '!=', null)->paginate(5);
        return view('livewire.charity.table', ['charities' => $charities]);
    }
}

app/Http/Livewire/Finotech/BankInfo.php
<?php

namespace App\Http\Livewire\Finotech;

use App\Http\Controllers\FinoTechController;
use App\Models\TokenFinotech;
use Carbon\Carbon;
use Livewire\Component;

class BankInfo extends Component
{
    public $bankInfos=array();
    public $message;

    public function checkTokenList()
    {
        $token = TokenFinotech::where("scopes", "like", "facility:cc-bank-info:get")->first();
        if (!$token) {
            $this->message = "توکن برای این درخواست موجود نمی باشد";
            return false;
        }
        $now = Carbon::now()->format('U');
        if ($now > $token->life_time) {
            $this->message = "تاریخ اعتبار توکن گذشته است";
            return false;
        }
        return true;
    }


    public function showList(){
        $finotech=new FinoTechController();
        $this->bankInfos=$finotech->getBankInfo();
    }

    public function render()
    {
        $showButton = $this->checkTokenList();
        return view('livewire.finotech.bank-info',['showButton' => $showButton]);
    }
}

app/Http/Livewire/Finotech/CodeAc.php
<?php

namespace App\Http\Livewire\Finotech;

use App\Models\CodeFinotech;
use Livewire\Component;
use Livewire\WithPagination;

class CodeAc extends Component
{
    use WithPagination;

    public $sortBy='updated_at';

    public function sort(){
    $this->sortBy="created_at";
    }

    public function render()
    {
        $lists=CodeFinotech::orderBy($this->sortBy)->paginate(20);
        return view('livewire.finotech.code-ac',['lists'=>$lists]);
    }
}

app/Http/Livewire/Finotech/ListCc.php
<?php

namespace App\Http\Livewire\Finotech;

use App\Http\Controllers\FinoTechController;
use App\Models\TokenFinotech;
use Carbon\Carbon;
use Livewire\Component;

class ListCc extends Component
{
    public $clientCredentials=array();
    public $message;

    public function checkTokenList()
    {
        $token = TokenFinotech::where("scopes", "like", "boomrang:tokens:get")->first();
        if (!$token) {
            $this->message="توکن برای این درخواست موجود نمی باشد";
            return false;
        }
        $now = Carbon::now()->format('U');
        if ($now > $token->life_time) {
            $this->message="تاریخ اعتبار توکن گذشته است";
            return false;
        }
        return true;
    }

    public function showList()
    {
        $finotech = new FinoTechController();
        $this->clientCredentials = $finotech->getListTokenCc();
    }


    public function render()
    {
        $showButton=$this->checkTokenList();
        return view('livewire.finotech.list-cc', ['clientCredentials' => $this->clientCredentials,'showButton'=>$showButton]);
    }
}

app/Http/Livewire/Finotech/ListWage.php
<?php

namespace App\Http\Livewire\Finotech;

use App\Http\Controllers\FinoTechController;
use App\Models\TokenFinotech;
use Carbon\Carbon;
use Livewire\Component;

class ListWage extends Component
{
    public $clientCredentials = array();
    public $message;

    public function checkTokenList()
    {
        $token = TokenFinotech::where("scopes", "like", "boomrang:wages:get")->first();
        if (!$token) {
            $this->message = "توکن برای این درخواست موجود نمی باشد";
            return false;
        }
        $now = Carbon::now()->format('U');
        if ($now > $token->life_time) {
            $this->message = "تاریخ اعتبار توکن گذشته است";
            return false;
        }
        return true;
    }

    public function showList()
    {
        $finotech = new FinoTechController();
        $this->clientCredentials = $finotech->getWages();
    }


    public function render()
    {
        $showButton = $this->checkTokenList();
        return view('livewire.finotech.list-cc', ['clientCredentials' => $this->clientCredentials, 'showButton' => $showButton]);
    }
}

app/Http/Livewire/Finotech/RightNavbarAc.php
<?php

namespace App\Http\Livewire\Finotech;

use Livewire\Component;

class RightNavbarAc extends Component
{
    public $tabs;

    public function __construct($id = null)
    {
        $this->tabs=['1'=>1,'2'=>0,'3'=>0];
    }

    public function showTab($numberTab){
        $this->tabs=array_fill(1, count($this->tabs), 0);
        $this->tabs[$numberTab]=1;
    }


    public function render()
    {
        return view('livewire.finotech.right-navbar-ac');
    }
}

app/Http/Livewire/Finotech/RightNavbarCc.php
<?php

namespace App\Http\Livewire\Finotech;

use Livewire\Component;

class RightNavbarCc extends Component
{
    public $tabs;

    public function __construct($id = null)
    {
        $this->tabs=['1'=>1,'2'=>0,'3'=>0,'4'=>0,'5'=>0,'6'=>0];
    }

    public function showTab($numberTab){
        $this->tabs=array_fill(1, count($this->tabs), 0);
        $this->tabs[$numberTab]=1;
    }

    public function render()
    {
        return view('livewire.finotech.right-navbar-cc');
    }
}

app/Http/Livewire/Map/AddMarker.php
<?php

namespace App\Http\Livewire\Map;

use Livewire\Component;

class AddMarker extends Component
{
    public $messages=[[36.289632, 59.616130]];
    public function render()
    {
        return view('livewire.add-marker');
    }
}

resources/views/livewire/finotech/bank-info.blade.php
<div>

    @if($showButton)
        <button wire:click="showList" class="btn btn-primary"
                style="color:white;font-size: 14px;margin: auto;margin-top: 10px;margin-bottom: 10px;display: block;">
            فراخوانی لیست بانک ها از API
        </button>
    @endif
    @if($message)
        <div class="alert alert-danger">{{$message}}</div>
    @endif
    <table class="table" style="font-size:14px;">
        <thead>
        <tr>
            <th><span style="cursor: pointer;" role="button" href="#">
                            فرمت شماره کارت
                        </span></th>
            <th><span role="button" href="#">
                            نام بانک
                        </span></th>
        </tr>
        </thead>
        <tbody style="">
        @foreach ($bankInfos as $bankInfo)
            <tr>
                <td>{{ $bankInfo->cardPrefix }}</td>
                <td>{{ $bankInfo->name }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

resources/views/livewire/finotech/code-ac.blade.php
<div>
    <table class="table" style="font-size:14px;">
        <thead>
        <tr>
            <th><span role="button" href="#">
                            scopes
                        </span></th>
            <th><span style="cursor: pointer;" wire:click.prevent="sort" role="button" href="#">
                            تاریخ ایجاد
                        </span></th>
        </tr>
        </thead>
        <tbody style="">
        @foreach ($lists as $list)
            <tr>
                <td>{{$list->code}}</td>
                <td>{{$list->created_at}}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
    {{ $lists->links("pagination::bootstrap-4") }}
</div>

resources/views/livewire/finotech/list-cc.blade.php
<div>
    @if($showButton)
        <button wire:click="showList" class="btn btn-primary" style="color:white;font-size: 14px;margin: auto;margin-top: 10px;margin-bottom: 10px;display: block;">فراخوانی توکن از API
        </button>
    @endif
    @if($message)
        <div class="alert alert-danger">{{$message}}</div>
    @endif
    <table class="table" style="font-size:14px;">
        <thead>
        <tr>
            <th><span style="cursor: pointer;" role="button" href="#">
                            تاریخ ایجاد
                        </span></th>
            <th><span role="button" href="#">
                            scopes
                        </span></th>
        </tr>
        </thead>
        <tbody style="">
        @foreach ($clientCredentials as $clientCredential)
            <tr>
                <td>{{ $clientCredential->creationDate }}</td>
                <td>{{ $clientCredential->scopes }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

resources/views/livewire/finotech/right-navbar-ac.blade.php
<div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <li class="btn btn-light" wire:click="showTab(1)" style="margin: 5px;font-size:14px;width:100%;">
                    نمایش url
                </li>
                <li class="btn btn-light" wire:click="showTab(2)" style="margin: 5px;font-size:14px;width:100%;">
                    نمایش لیست کدها
                </li>
                <li class="btn btn-light" wire:click="showTab(3)" style="margin: 5px;font-size:14px;width:100%;">
                    نمایش لیست توکن ها
                </li>
            </div>
            <div class="col-lg-9">
                @if($tabs[1])
                    <div>
                        @livewire('finotech.url-ac')
                    </div>
                @endif
                @if($tabs[2])
                    <div>
                        @livewire('finotech.code-ac')
                    </div>
                @endif
                @if($tabs[3])
                    <div>
                        @livewire('finotech.table-ac')
                    </div>
                @endif
            </div>
        </div>
    </div>
</div>

resources/views/livewire/finotech/right-navbar-cc.blade.php
<div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <li class="btn btn-light" wire:click="showTab(1)" style="margin: 5px;font-size:14px;width:100%;">
                    نمایش فرم
                </li>
                <li class="btn btn-light" wire:click="showTab(2)" style="margin: 5px;font-size:14px;width:100%;">
                    نمایش جدول توکن ها
                </li>
                <li class="btn btn-light" wire:click="showTab(3)" style="margin: 5px;font-size:14px;width:100%;">
                    نمایش لیست توکن ها با استفاده از API
                </li>
                <li class="btn btn-light" wire:click="showTab(4)" style="margin: 5px;font-size:14px;width:100%;">
                    نمایش کارمزد ها با استفاده از API
                </li>
                <li class="btn btn-light" wire:click="showTab(5)" style="margin: 5px;font-size:14px;width:100%;">
                    نمایش کارت ها
                </li>
                <li class="btn btn-light" wire:click="showTab(6)" style="margin: 5px;font-size:14px;width:100%;">
                    نمایش بانک ها با استفاده از API
                </li>
            </div>
            <div class="col-lg-9">
                @if($tabs[1])
                    <div>
                        @livewire('finotech.select-cc')
                    </div>
                @endif
                @if($tabs[2])
                    <div>
                        @livewire('finotech.table-cc')
                    </div>
                @endif
                @if($tabs[3])
                    <div>
                        @livewire('finotech.list-cc')
                    </div>
                @endif
                @if($tabs[4])
                    <div>
                        @livewire('finotech.list-wage')
                    </div>
                @endif
                @if($tabs[5])
                    <div>
                        @livewire('finotech.table-card')
                    </div>
                @endif
                @if($tabs[6])
                    <div>
                        @livewire('finotech.bank-info')
                    </div>
                @endif
            </div>
        </div>
    </div>
</div>

resources/views/livewire/finotech/select-cc.blade.php
<div>
    <div>
        @foreach($index_scopes as $index=>$value)
            <button class="btn btn-light" style="font-size:14px;margin: 5px;"
                    wire:click="selectScope({{$index}})">{{$value}}</button>
        @endforeach
    </div>
    <div>
        @foreach($selected_scopes as $index=>$selected_scope)
            <button class="btn btn-success" style="font-size:14px;color:white;margin: 5px"
                    wire:click="removeScope({{$index}})">{{$selected_scope}}</button>
        @endforeach
    </div>
    <div>
        <button class="btn btn-danger" wire:click.pervent="saveClienCredentical()" style="font-size:18px">ذخیره</button>
    </div>
</div>

resources/views/livewire/finotech/table-ac.blade.php
<div>
    <div class="container">
        <div class="row">
            <table class="table" style="font-size:14px;">
                <thead>
                <tr>
                    <th><span role="button" href="#">
                            scopes
                        </span></th>
                    <th><span style="cursor: pointer;" wire:click.prevent="sortBy('life_time')" role="button" href="#">
                            تاریخ اعتبار
                        </span></th>
                    <th><span role="button" href="#">
                            تاریخ ایجاد
                        </span></th>
                    <th><span role="button" href="#">
                            ویرایش
                        </span></th>
                </tr>
                </thead>
                <tbody style="">
                @foreach ($tokens as $token)
                    <tr>
                        <td>{{ $token->scopes }}</td>
                        <td style="text-align: left;direction: ltr">{{ $token->life_time}}</td>
                        <td style="text-align: left;direction: ltr">{{ $token->creation_date }}</td>
                        <td>
                            @if($checkDeleteToken)
                                <span class="btn btn-danger" wire:click="delete({{$token->id}})">حذف</span>
                            @endif
                            <span class="btn btn-success" wire:click="refreshToken({{$token->id}})">تمدید</span>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        {{ $tokens->links("pagination::bootstrap-4") }}
        <div class="col text-right text-muted">
            Showing {{ $tokens->firstItem() }} to {{ $tokens->lastItem() }} out of {{ $tokens->total() }} results
        </div>
        <div class="alert alert-light">{{$response}}</div>
    </div>
</div>

resources/views/livewire/finotech/table-card.blade.php
<div>
    <div class="container">
        <div class="row">
            <table class="table" style="font-size:14px;direction: ">
                <thead>
                <tr>
                    <th><span style="cursor: pointer;direction: ltr" wire:click.prevent="sortBy('created_at')" role="button" href="#">
                            تاریخ ایجاد
                        </span></th>
                    <th><span role="button" href="#">
                            شماره کارت
                        </span></th>
                    <th><span role="button" href="#">
                            نام
                        </span></th>
                    <th><span role="button" href="#">
                            شماره موبایل فرد درخواست دهنده
                        </span></th>
                </tr>
                </thead>
                <tbody style="">
                @foreach ($cardInfoes as $cardInfo)
                    <tr>
                        <td style="direction: ltr">{{ $cardInfo->do_time }}</td>
                        <td style="text-align: center;">{{ $cardInfo->card_number}}</td>
                        <td style="text-align: center;">{{ $cardInfo->name }}</td>
                        <td style="text-align: center;">{{ $cardInfo->name }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        {{ $cardInfoes->links("pagination::bootstrap-4") }}
        <div class="col text-right text-muted">
            Showing {{ $cardInfoes->firstItem() }} to {{ $cardInfoes->lastItem() }} out of {{ $cardInfoes->total() }} results
        </div>
    </div>
</div>

resources/views/livewire/finotech/table-cc.blade.php
<div>
    <div class="container">
        <div class="row">
            <table class="table" style="font-size:14px;">
                <thead>
                <tr>
                    <th><span role="button" href="#">
                            scopes
                        </span></th>
                    <th><span style="cursor: pointer;" wire:click.prevent="sortBy('life_time')" role="button" href="#">
                            تاریخ اعتبار
                        </span></th>
                    <th><span role="button" href="#">
                            تاریخ ایجاد
                        </span></th>
                    <th><span role="button" href="#">
                            ویرایش
                        </span></th>
                </tr>
                </thead>
                <tbody style="">
                @foreach ($tokens as $token)
                    <tr>
                        <td>{{ $token->scopes }}</td>
                        <td style="text-align: left;direction: ltr">{{ $token->life_time}}</td>
                        <td style="text-align: left;direction: ltr">{{ $token->creation_date }}</td>
                        <td>
                            @if($checkDeleteToken)
                                <span class="btn btn-danger" wire:click="delete({{$token->id}})">حذف</span>
                            @endif
                            <span class="btn btn-success" wire:click="refreshToken({{$token->id}})">تمدید</span>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        {{ $tokens->links("pagination::bootstrap-4") }}
        <div class="col text-right text-muted">
            Showing {{ $tokens->firstItem() }} to {{ $tokens->lastItem() }} out of {{ $tokens->total() }} results
        </div>
        <div class="alert alert-light">{{$response}}</div>
    </div>
</div>

resources/views/livewire/finotech/url-ac.blade.php
<div>
    @foreach($indexScopes as $key=>$indexScope)
        <a class="btn btn-light" style="font-size:14px" href="{{"https://apibeta.finnotech.ir//dev/v2/oauth2/authorize?client_id=newcash1&response_type=code&redirect_uri=https://new-cash.ir/bank-confirmation&scope={$valueScopes[$key]}&limit=100000000&count=1000&bank=062"}}">{{$indexScope}}</a>
    @endforeach
</div>