routes/web.php
<?php

use App\Models\User;
use Carbon\Carbon;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/home', 'HomeController@index')->name('home');

/*
|--------------------------------------------------------------------------
| Login And Registration System
|--------------------------------------------------------------------------
*/

Route::get('/login', 'UserController@login')->name('user.login');
Route::get('/verify', 'UserController@createToken')->name('user.createToken');
Route::any('/accept', 'UserController@checkToken')->name('user.checkToken');
Route::any('/marketer/store', 'UserController@marketerStore')->name('user.marketerStore');
Route::any('list', 'UserController@list')->name('user.list');
Route::any('listMarketer', 'UserController@listMarketer')->name('user.listMarketer');
Route::any('/insertajax', 'UserController@insertajax')->name('user.insertajax');
Route::any('update', 'UserController@update')->name('user.update');
Route::any('updateUser', 'UserController@editUser')->name('user.editUser');
Route::any('insertUser', 'UserController@createUser')->name('user.createUser');
Route::delete('delete', 'UserController@delete')->name('user.delete');
/*
|--------------------------------------------------------------------------
| Url Create
|--------------------------------------------------------------------------
*/
Route::any('/url', 'UrlGeneratorController@create');
Route::any('/p{url?}', 'UrlGeneratorController@createPaymentLink');

/*
|--------------------------------------------------------------------------
| Transaction System
|--------------------------------------------------------------------------
*/

Route::any('/transaction/insert/', 'TransactionController@store');
Route::any('/transaction/list/', 'TransactionController@list')->name('Transaction.list');
Route::any('/transaction/listMarketer/', 'TransactionController@list2')->name('Transaction.listForMarketer');
Route::any('/transaction/detailList/', 'TransactionController@detailList')->name('Transaction.detailList');
/*
|--------------------------------------------------------------------------
| PanelUserController
|--------------------------------------------------------------------------
*/

Route::prefix('panel/user')->name('panel.user.')->namespace('panel')->group(function () {
    Route::get('insert', 'UserPanelController@insert')->name('insert');
    Route::post('store', 'UserPanelController@store')->name('store');
    Route::any('update', 'UserPanelController@update')->name('update');
    Route::any('updatePass', 'UserPanelController@updatePass')->name('updatePass');
    Route::any('RestorePass', 'UserPanelController@RestorePass')->name('RestorePass');
    Route::any('delete', 'UserPanelController@delete')->name('delete');
    Route::any('list', 'UserPanelController@list')->name('list');
    Route::any('/listhome', 'UserPanelController@listhome')->name('listhome');
    Route::any('show', 'UserPanelController@show')->name('show');
    Route::get('login', function () {
        return view('panel.login');
    });
    Route::any('/insert', 'UserPanelController@insert')->name('insert');
    Route::any('/insertajax', 'UserPanelController@insertajax')->name('insertajax');
    Route::post('storeUser', 'UserPanelController@storeUser')->name('storeUser');
    Route::any('/updateajax', 'UserPanelController@updateAjax')->name('updateAjax');
    Route::any('login', 'UserPanelController@login')->name('login');
    Route::get('login', 'UserPanelController@logout')->name('logout');
    Route::any('home', 'UserPanelController@home')->name('home');
    Route::any('permission', 'UserPanelController@permission')->name('permission');
    // Route::any('home', 'UserPanelController@home')->name('home');
});

/*
|--------------------------------------------------------------------------
//GroupController
|--------------------------------------------------------------------------
*/

Route::prefix('panel/group')->name('panel.group.')->namespace('panel')->group(function () {
    Route::get('insert/', 'GroupController@insert')->name('insert')->middleware('permission:GroupController@insert');
    Route::post('insert/', 'GroupController@store')->name('store')->middleware('permission:GroupController@store');
    Route::put('edit/', 'GroupController@update')->name('update')->middleware('permission:GroupController@update');
    Route::delete('delete/', 'GroupController@delete')->name('delete')->middleware('permission:GroupController@delete');
    Route::get('show/{Group}', 'GroupController@show')->name('show')->middleware('permission:GroupController@show');
});

/*
|--------------------------------------------------------------------------
| UserGroupController
|--------------------------------------------------------------------------
*/

Route::prefix('panel/user-group')->name('panel.usergroup.')->namespace('panel')->group(function () {
    Route::get('insert/', 'UserGroupController@insert')->name('insert')->middleware('permission:UserGroupController@insert');
    Route::post('insert/', 'UserGroupController@store')->name('store')->middleware('permission:UserGroupController@store');
    Route::put('edit/', 'UserGroupController@update')->name('update')->middleware('permission:UserGroupController@update');
    Route::delete('delete/', 'UserGroupController@delete')->name('delete')->middleware('permission:UserGroupController@delete');
    Route::get('show/{UserGroup}', 'UserGroupController@show')->name('show')->middleware('permission:UserGroupController@show');
});

/*
|--------------------------------------------------------------------------
//MethodController
|--------------------------------------------------------------------------
*/

Route::prefix('panel/method')->name('panel.method.')->namespace('panel')->group(function () {
    Route::get('insert/', 'MethodController@insert')->name('insert')->middleware('permission:MethodController@insert');
    Route::post('insert/', 'MethodController@store')->name('store');
    Route::put('edit/', 'MethodController@update')->name('update');
    Route::delete('delete/', 'MethodController@delete')->name('delete');
    Route::get('show/', 'MethodController@show')->name('show');
});


/*
|--------------------------------------------------------------------------
/PermissionGroupController
|--------------------------------------------------------------------------
*/

Route::prefix('panel/permission-group')->name('panel.permissiongroup.')->namespace('panel')->group(function () {
    Route::any('insert/', 'PermissionGroupController@insert')->name('insert')->middleware('permission:PermissionGroupController@insert');
    Route::post('insert/', 'PermissionGroupController@store')->name('store')->middleware('permission:PermissionGroupController@insert');
    Route::put('edit/', 'PermissionGroupController@update')->name('update')->middleware('permission:PermissionGroupController@insert');
    Route::delete('delete/', 'PermissionGroupController@delete')->middleware('permission:PermissionGroupController@insert');
    Route::get('show/', 'PermissionGroupController@show')->middleware('permission:PermissionGroupController@insert');
    Route::any('/ajax', 'PermissionGroupController@ajax')->name('ajax');
    Route::any('insertajax/', 'PermissionGroupController@ajaxStore')->name('ajaxStore')->middleware('permission:PermissionGroupController@ajaxStore');
});


/*
|--------------------------------------------------------------------------
//PermissionUserController
|--------------------------------------------------------------------------
*/

Route::prefix('panel/permission-user')->name('panel.permissionuser.')->namespace('panel')->group(function () {
    Route::any('insert/', 'PermissionUserController@insert')->name('insert');
    Route::post('insert/', 'PermissionUserController@store')->name('store');
    Route::put('edit/', 'PermissionUserController@update');
    Route::delete('delete/', 'PermissionUserController@delete');
    Route::get('show/', 'PermissionUserController@show');
    Route::any('/ajax', 'PermissionUserController@ajax')->name('ajax');

});

/*
 * //TaxiController

 */
Route::prefix('panel/taxi')->name('panel.taxi.')->namespace('panel')->group(function () {
    Route::any('requestTaxi/', 'TaxiController@request')->name('request');
    Route::any('chooseSelectedPlace/','TaxiController@chooseSelectedPlace')->name('chooseSelectedPlace');
    Route::any('calculatePrice/', 'TaxiController@calculatePrice')->name('calculatePrice');
    Route::any('requestService/', 'TaxiController@requestService')->name('requestService');
    Route::any('requestRefresh/', 'TaxiController@requestRefresh')->name('requestRefresh');
    Route::any('search/', 'TaxiController@search')->name('search');
    Route::any('storeTrip/', 'TaxiController@storeTrip')->name('storeTrip');
    Route::any('storeSelectedPlace/','TaxiController@storeSelectedPlace')->name('storeSelectedPlace');
    Route::any('currentRequest/','TaxiController@currentRequest')->name('currentRequest');
    Route::any('countRequest/','TaxiController@countRequest')->name('countRequest');
});
/*
|--------------------------------------------------------------------------
|  //tourism
|--------------------------------------------------------------------------
*/

Route::prefix('panel/tourism')->name('panel.tourism.')->namespace('panel')->group(function () {
    Route::any('storeTypeCategory/', 'tourismController@storeTypeCategory')->name('storeTypeCategory');
    Route::any('typeCategory/', 'tourismController@typeCategory')->name('typeCategory');

app/Models/PermissionGroup.php
<?php

namespace App\Models;

use App\Http\Requests\PermissinGroupPanelRequest;
use Illuminate\Database\Eloquent\Model;

class PermissionGroup extends Model
{
    protected $primaryKey="permission_group_id";
    protected $table='pl_permission_groups';
    protected $guarded = ['id'];
}

app/Http/Controllers/Panel/GroupController.php
<?php

namespace App\Http\Controllers\Panel;
use App\Http\Requests\GroupPanelRequest;
use App\Models\Group;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class GroupController extends Controller
{
    public function insert(){
        return view('panel.group.insert');
    }
    public function store(GroupPanelRequest $request){
        Group::create($request->all());
    }
    public function delete(Request $request){
        Group::find($request->group_id)->delete();
    }
    public function update(GroupPanelRequest $request){
        Group::update([
            'name'=>$request->name
        ]);
    }
    public function show(App\Group $grouppanel){
    }
}

app/Http/Controllers/Panel/MethodController.php
<?php

namespace App\Http\Controllers\Panel;
use App\Http\Requests\MethodPanelRequest;
use App\Models\Method;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class MethodController extends Controller
{
    public function insert(){
        return view('panel.method');
    }

    public function store(MethodPanelRequest $request){
        Method::create($request->all());
    }
    public function delete(Request $request){
        Method::find($request->method_id)->delete();
    }
    public function update(MethodPanelRequest $request){
        Method::update([
            'title'=>$request->title
        ]);
    }
    public function show(App\Mehod $Method){
    }
}

app/Http/Controllers/Panel/PermissionGroupController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Group;
use App\Http\Requests\PermissinGroupPanelRequest;
use App\Models\Method;
use App\Models\PermissionGroup;
use App\Models\PermissionUser;
use App\Models\UserPanel;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PermissionGroupController extends Controller
{
    public function insert(){

        $method=Method::all();
        $groups=Group::all();
        $all = PermissionGroup::select('*')
            ->rightJoin('pl_methods', function($join) {
                $join->on('pl_permission_groups.method_id', '=', 'pl_methods.method_id');})->get();
        return view('panel.permissiongroup.insert', ['groups' => $groups,'methods'=>$method,'all'=>$all]);
    }

    public function store(PermissinGroupPanelRequest $request){
        PermissionGroup::where('group_id',$request->group_id)->delete();
        if($request->status) {
            foreach ($request->status as $key => $index) {
                PermissionGroup::create([
                    'group_id' => $request->group_id,
                    'method_id' => $key,
                    'status' => $index
                ]);
            }
        }
    }
    public function ajaxStore()
    {
        PermissionGroup::where('group_id',request()->group_id)->delete();
        $method_id="";
        $formData = $_POST['myCheckboxes'];
        foreach ($formData as $key => $index) {
            if(str_contains($index,'myCheckboxes%5B%5D')) {
                $method_id =   str_replace("myCheckboxes%5B%5D=", "", $index);
                PermissionGroup::create([
                    'group_id' => request()->group_id,
                    'method_id' => $method_id,
                    'status' => 1
                ]);
            }
        }
        $returnHTML = view('panel.permissiongroup.success', ['group_id' => request()->group_id])->render();
        return response()->json($returnHTML);
        /* if (true) {
             $returnHTML = view('panel.permissiongroup.success', ['group_id' => request()->group_id])->render();

             return response()->json($returnHTML);
         } else {
             return false;
         }*/
        /*PermissionGroup::where('group_id',request()->group_id)->delete();
        if(request()->status) {
            foreach (request()->status as $key => $index) {
                PermissionGroup::create([
                    'group_id' => request()->group_id,
                    'method_id' => $key,
                    'status' => $index
                ]);
            }
        }
        if (true) {
            $returnHTML = view('panel.permissiongroup.success', ['group_id' => request()->group_id])->render();

            return response()->json($returnHTML);
        } else {
            return false;
        }*/
    }
    public function delete(Request $request){
        PermissionGroup::get($request->permission_group_id)->delete();
    }
    public function update(PermissinGroupPanelRequest $request){
        PermissionGroup::update([
            'status'=>$request->status
        ]);
    }

    public function show(App\PermissionGroup $PermissionGroup){
    }
    public function ajax()
    {
        $method=Method::all();
        $all_permission = PermissionGroup::select('*')
            -> rightJoin('pl_methods', function($join) {
                $join->on('pl_permission_groups.method_id', '=', 'pl_methods.method_id')
                    ->where('pl_permission_groups.group_id', '=' , request()->group_id);
            })
            ->get();
        if (true) {
            $returnHTML = view('panel.permissiongroup.ajax', ['group_id' => request()->group_id, 'all_permission'=> $all_permission,'methods'=>$method])->render();
            return response()->json($returnHTML);
        } else {
            return false;
        }
    }
    public function test(){
        $methodAll=Method::get();
        $method=Method::get('method_id');
        $all_permission = PermissionGroup::select('*')
            -> leftJoin('pl_methods', function($join) {
                $join->on('pl_permission_groups.method_id', '=', 'pl_methods.method_id');})->where('pl_permission_groups.group_id',1)->get();
        $methods=$method->toarray();

        foreach ($methods as $item){

            if ( in_array($item, $all_permission->toarray())){

            }

        }

    }

}

app/Http/Controllers/Panel/Taxi.php
<?php

namespace App\Http\Controllers\Panel;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class Taxi extends Controller
{
    //
}

app/Http/Controllers/Panel/UserGroupController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Models\Group;
use App\Http\Requests\UserGroupPanelRequest;
use App\Models\User;
use App\Models\UserGroup;
use App\Models\UserPanel;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Http\Controllers\Controller;

class UserGroupController extends Controller
{
    public function insert(){
        $users=UserPanel::all();
        $groups=Group::all();
        return view('panel.usergroup.insert', ['users' => $users,'groups'=>$groups]);
    }

    public function store(UserGroupPanelRequest $request){
        UserGroup::create($request->all());
    }

    public function delete(Request $request){
        UserGroup::find($request->user_group_id)->delete();
    }

    public function update(UserGroupPanelRequest $request){

    }


    public function show(App\UserGroup $UserGroup){
    }
}

resources/views/panel/permissiongroup/ajax.blade.php
<div class="form-group col-lg-4" name="access">

    @foreach ($all_permission  as $d)
{{--
        @if ($d['status']==1)
            <input type="hidden"   name="method_id[{{$d['method_id']}}]"  value= {{$d['method_id']}}  >
            <input type="checkbox" name="status[{{$d['method_id']}}]"     value='1'  checked="">
        @else
            <input type="hidden"   name="method_id[{{$d['method_id']}}]"  value= {{$d['method_id']}}  >
            <input type="checkbox" name="status[{{$d['method_id']}}]"     value='1'  {{ old('status') ? 'checked' : '' }} >
        @endif--}}
            @if ($d['status']==1)
                <input type="hidden"   name="method_id[{{$d['method_id']}}]"  value= {{$d['method_id']}}  >
                <input type="checkbox"  id="myCheckboxes"  name="myCheckboxes[]"      value= {{$d['method_id']}} checked="">
            @else
                <input type="hidden"   name="method_id[{{$d['method_id']}}]"  value= {{$d['method_id']}}  >
                <input type="checkbox" id="myCheckboxes" name="myCheckboxes[]"     value= {{$d['method_id']}} {{ old('status') ? 'checked' : '' }} >
            @endif

        {{ ($d['title'])}}<br>
    @endforeach


</div>

resources/views/panel/permissiongroup/insert.blade.php
@extends('layouts.app')
@section('content')
    <div class="container form-otah">
        <form enctype="multipart/form-data" name="myform" method="post" action="{{route('panel.permissiongroup.store')}}" >
            @csrf
            <h1 class="titr">دسترسی گروه ها</h1>
            <hr>
            <div >
                <div class="form-group col-lg-4">
                    <select name="group_id" class="form-control" onchange="selectGroup()">
                        @foreach ($groups as $group)
                            <option value="{{$group->group_id}}">{{$group->name}}</option>
                        @endforeach
                    </select>
                </div>
                <div id="g_permission">
                </div>
              {{-- <button class="btn btn-success" type="submit" style="height: 40px;">ارسال</button>--}}
               <button class="btn btn-success" type="button"  onclick="save()" style="height: 40px;">ارسال</button>

            </div>
        </form>
    </div>
    <div id="g_result">
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
@endsection
@section('script')
    <script  type="text/javascript" src="jquery-3.5.1.min.js"></script>
    <script type="text/javascript">
       var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
       function selectGroup() {
           var group_id =  $('select[name="group_id"]').val();
           $.ajax({
               url: '{{route('panel.permissiongroup.ajax')}}',
               type: 'POST',
               data: {
                   _token: CSRF_TOKEN,
                   group_id: group_id
               },
               dataType: 'json',
               success: function(data ) {
                   $('#g_permission').html(data);
               }
           });
       }
      /* function save() {
           var group_id =  $('select[name="group_id"]').val();
           var status =  $('checkbox[name="status[1]"]').val();
           alert(status);
           $.ajax({
               //url:
               type: 'POST',
               data: {
                   _token: CSRF_TOKEN,
                   group_id: group_id,
                   status:status,

               },
               dataType: 'json',
               success: function(data ) {
                   $('#g_result').html(data);
               }
           });
       }*/
       function save() {
           var group_id =  $('select[name="group_id"]').val();
           var arr = $('input[name="myCheckboxes[]"]').map(function(){
               var dataString = $(this).serialize();
               return dataString;
           }).get();
           $.ajax({
               type: "POST",
               url:  '{{route('panel.permissiongroup.ajaxStore')}}',
               dataType: 'html',
               data: {myCheckboxes:arr ,group_id:group_id},
               dataType: 'json',
               success: function(data ) {
                   $('#g_result').html(data);
               }
           });
           return false;
       }


    </script>
@endsection

resources/views/panel/permissiongroup/success.blade.php
<div class="form-group col-lg-4" name="access">
 اطلاعات با موفقیت ثبت شد


</div>